# This is just an example workflow for continous deployment.
# You should customize it to meet your own requirements.
name: 'Continuous Deployment'
on:
  # When new commits are pushed onto the main branch.
  push:
    branches:
      - main
jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    environment: test_environment
    env:
      AZURE_ACCOUNT_NAME: ${{secrets.AZURE_ACCOUNT_NAME}}
      AZURE_ACCOUNT_PASSWORD: ${{secrets.AZURE_ACCOUNT_PASSWORD}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      M365_ACCOUNT_NAME: ${{secrets.M365_ACCOUNT_NAME}}
      M365_ACCOUNT_PASSWORD: ${{secrets.M365_ACCOUNT_PASSWORD}}

      # If the hosting environment is not provisioned, set this environment variable to true.
      # or if it's provisioned and has not updates, set this environment variable to false.
      RUN_PROVISION: true 

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Provision hosting environment
        if: env.RUN_PROVISION == 'true'
        uses: OfficeDev/teamsfx-cli-action@v0
        with:
          commands: provision
          subscription: ${{env.AZURE_SUBSCRIPTION_ID}}

      - name: Commit provision configs if necessary
        if: env.RUN_PROVISION == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: commit provision configs"
          file_pattern: .fx/*

      - name: Deploy to hosting environment
        uses: OfficeDev/teamsfx-cli-action@v0
        with:
          commands: deploy

      - name: Validate Teams App's manifest
        uses: OfficeDev/teamsfx-cli-action@v0
        with:
          commands: validate

      - name: Build Teams App's package
        uses: OfficeDev/teamsfx-cli-action@v0
        with:
          commands: build

      - name: Upload Teams App's package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: appPackage
          path: ./.fx/appPackage.zip

      - name: Publish Teams App
        uses: OfficeDev/teamsfx-cli-action@v0
        with:
          commands: publish
